name: build-rockchip-immortalWrt-R1
on:
  workflow_dispatch:
    inputs:
      luci_version:
        description: "选择LuCI版本"
        default: "openwrt-24.10.x"
        type: choice
        options:
          - openwrt-24.10.x
          - openwrt-24.09.x
          - openwrt-23.05.x
      profile:
        description: "设备型号"
        default: "friendlyarm_nanopi-r1"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: bev

      - name: Prepare build environment
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget

      - name: Build firmware for NanoPi R1
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ../configs/friendlyarm_nanopi-r1.config .config
          make defconfig
          make download -j$(nproc)
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: NanoPi-R1-firmware
          path: immortalwrt/bin/targets/*/*/*.img.gz
